version: '2'
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
  web:
    build: .
    volumes:
      - /app/log
    depends_on:
      - db
  nginx:
    build: containers/nginx
    ports:
      - "80:80"
    volumes_from:
      - web
    depends_on:
      - web